<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
	<title>bon de commande</title>
	<link rel="stylesheet" type="text/css" href="bon.css">
</head>
<body>
    <h1>Bon de commande</h1>

     <h1 class="center">Liste de commande</h1>
 
<table>
  <th>commande</th>
  <th>date de commande</th>
  <th>date de livraison</th>
  <th>statut</th>

   <?php foreach ($offices as $val) :?>
   
   <tr> 
      
        <td> <a href="get.php?orderNumber=<?= $val['orderNumber'] ?>"><?= $val['orderNumber'] ?> </a> </td>
        <td> <?= $val['orderDate'] ?> </td>
        <td> <?= $val['requiredDate'] ?> </td>
        <td> <?= $val['status'] ?> </td>

    </tr>

    <?php endforeach ?>
</table>




</body>
</html>