
<!DOCTYPE html>
<html>
<head>
	<title>traducteur Anglais-Francais</title>
</head>
<body>
   <h1>traducteur</h1>
   <form action="traducteur.php" method="post">
    <div>
        <label for="word"> mot:</label>
        <input type="text">
        <button> Traduire</button>
    </div>
        <label for="trad"> sens de traduction :</label>
        <select name="value">
			<option value="value to english">Français vers Anglais</option>
			<option value="value to french">Anglais vers Français</option>
		</select>
   </form>
</body>
</html>