 <form class="generic-form" action="addpost.php" method="post">
    <fieldset>
        <legend><i class="fa fa-sticky-note-o"></i> Nouvel article</legend>
        <ul>
            <li>
                <label for="title">Titre :</label>
                <input type="text" id="title" name="title">
            </li>
            <li>
                <label class="textarea" for="commentaire">Article :</label>
                <textarea id="commentaire" name="commentaire" rows="15"></textarea>
            </li>
            <li>
                <label for="author">Auteur :</label>
            

             <select id="author" name="author">
         <?php foreach ($authors as $author): ?>
          <option value="<?=$author['Id']?>"><?= $author['FirstName'].' '.$author['LastName']?></option>
                    <?php endforeach ?>
                </select>


            </li>



            <li>
                <label for="category">Catégorie :</label>
                <select id="category" name="category">
                    <?php foreach ($categories as $category): ?>
                        <option value="<?=$category['Id']?>"><?= $category['Name']?></option>
                    <?php endforeach ?>
                </select>
            </li>
            
         
            <li>
                <button class="button button-primary" type="submit" href="addpost.php">Enregistrer</button>

                <a class="button button-cancel" href="index.php">Annuler</a>
            </li>
        </ul>
    </fieldset>
</form>
