<h2<i class="fas fa-home"></i>>Acceuil</h2>


<ul>  

                                       
    <?php foreach($liste as $value) :?>
        <li>
            <a href="show_post.php?id=<?=$value['Id']?>"> <?=$value['Title']?> </a>
            <p><?=$value['Contents']?></p>
            <p><?=$value['FirstName']?></p>
            <p><?=$value['LastName']?></p>
            <p><?=$value['CreationDate']?></p>
            
            
        </li>        
        
    <?php endforeach?>

    

 </ul>