
<h2><i class="fa fa-pencil"></i> Connectez vous </h2>




<form class="generic-form" action="login.php" method="post">
    <fieldset>
        <legend><i class="fa fa-sticky-note-o"></i> Nouvel utilisateur</legend>
        <ul>
            <li>
                <label for="Mail"> Email :</label>
                <input type="text" id="Mail" name="Mail">
            </li>
            <li>
                <label for="password">Mot de Passe :</label>
                <input type="password" id="password" name="Password">
            </li>
            <li>
                <button class="button button-primary" type="submit">Connexion</button>
                <a class="button button-cancel" href="index.php">Annuler</a>
            </li>
        </ul>
    </fieldset>
</form>
