
        
<h2><i class="fa fa-pencil"></i> Enregistrez vous </h2>


<form class="generic-form" action="register.php" method="post">
    <fieldset>
        <legend><i class="fa fa-sticky-note-o"></i> Nouvel utilisateur</legend>
        <ul>
            <li>
                <label for="lastName">Nom :</label>
                <input type="text" id="LastName" name="LastName">
            </li>
            <li>
                <label for="FirstName">Prénom :</label>
                <input type="text" id="FirstName" name="FirstName">
            </li>
            <li>
                <label for="Pseudo">Pseudo :</label>
                <input type="text" id="Pseudo" name="Pseudo">
            </li>
            <li>
                <label for="Mail">Email :</label>
                <input type="text" id="Mail" name="Mail">
            </li>
            <li>
                <label for="Password">Mot de Passe :</label>
                <input type="password" id="Password" name="Password">
            </li>
            <li>
                <button class="button button-primary" type="submit">Bienvenue</button>
                <a class="button button-cancel" href="index.php">Annuler</a>
            </li>
        </ul>
    </fieldset>
</form>
