<!-- Message de notification -->

<!-- Code HTML à écrire -->


<!-- Liste des aliments -->
<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody>
        <!-- Code HTML à écrire -->
        
        <?php foreach ($meals as $meal){ ?>
            <tr>
                <td><img src="<?=$wwwUrl?>/images/meals/<?=$meal['Photo']?>" alt=""/></td>
                <td><strong><?=$meal['Name']?></strong><br><?=$meal['Description']?></td>
                <td class="number"><strong><?= number_format($meal['SalePrice'], 2) ?></strong> €</td>
            </tr>
        <?php } ?>
        
    </tbody>
</table>